services:
  private-gpt:
    build:
      dockerfile: Dockerfile.external
#      dockerfile: Dockerfile.gpu
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./models:/root/.ollama
