### IMPORTANT, THIS IMAGE CAN ONLY BE RUN IN LINUX DOCKER
### You will run into a segfault in mac
FROM python:3.11.6-slim-bookworm as base

# Install poetry
RUN pip install pipx
RUN python3 -m pipx ensurepath
RUN pipx install poetry
ENV PATH="/root/.local/bin:$PATH"
ENV PATH=".venv/bin/:$PATH"

# Dependencies to build llama-cpp
RUN apt update && apt install -y \
  libopenblas-dev\
  ninja-build\
  build-essential\
  pkg-config\
  wget

# https://python-poetry.org/docs/configuration/#virtualenvsin-project
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

FROM base as dependencies
WORKDIR /home/worker/app
COPY pyproject.toml poetry.lock ./

RUN poetry install --with local
RUN poetry install --with ui

# Optional install:  # TODO test if it works
RUN pip3 install docx2txt

# TODO what does line below do?
FROM base as app
WORKDIR /home/worker/app

ENV PYTHONUNBUFFERED=1
ENV PORT=8080
EXPOSE 8080

# Prepare a non-root user
RUN adduser worker

# Special dirs
RUN mkdir -p .config/matplotlib; chown worker .config/matplotlib; chmod 770 .config/matplotlib
ENV MPLCONFIGDIR="/home/worker/app/.config/matplotlib"
RUN mkdir -p .cache/transformers; chown worker .cache/transformers; chmod 770 .cache/transformers
ENV TRANSFORMERS_CACHE="/home/worker/app/.cache/transformers"


RUN mkdir local_data; chown worker local_data
RUN mkdir -p models/cache; chown -R worker models; chmod -R 770 models
# TODO why would you copy .venv if at the top of the dockerfile you already do RUN poetry install ?....
COPY --chown=worker --from=dependencies /home/worker/app/.venv/ .venv
COPY --chown=worker private_gpt/ private_gpt
# TODO don't copy fern? is documentation only ... (check if fastapi doc page is still available)
COPY --chown=worker fern/ fern
COPY --chown=worker *.yaml *.md ./
COPY --chown=worker scripts/ scripts

ENV PYTHONPATH="$PYTHONPATH:/private_gpt/"

# TODO copying again to fix certain problem, must be solvable in a more logic way (e.g. only chown?)
COPY --chown=worker pyproject.toml ./

# TODO should be able to remove line below I believe
RUN chown -R worker private_gpt

# USER worker

# TODO fix it so that after setup we change to user worker? or so that the setup can be ran as user worker?
# TODO "force_download" option false each time => files shouldn't be reran if volumes mounted nicely? ... (except for tokenizer)
ENTRYPOINT poetry run python scripts/setup && su worker -c "python -m private_gpt"