server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: llamacpp
  max_new_tokens: 256  # the max number of new tokens the LLM will generate and add to the context window (by default Llama.cpp uses 256)
  context_window: 4096  # 4096 is the same as chatgpt. file(s) /w more tokens? => windowsing / chunking
  tokenizer: mistralai/Mistral-7B-Instruct-v0.2  # only needed for setup script (if llama-cpp)

llamacpp:
  prompt_style: chatml
  llm_hf_repo_id: ${PGPT_HF_REPO_ID:TheBloke/Mistral-7B-Instruct-v0.1-GGUF}
  llm_hf_model_file: ${PGPT_HF_MODEL_FILE:mistral-7b-instruct-v0.1.Q4_K_M.gguf}

huggingface:
  embedding_hf_model_name: ${PGPT_EMBEDDING_HF_MODEL_NAME:BAAI/bge-small-en-v1.5}

ui:
  default_chat_system_prompt: >
    You are a helpful and honest electrical engineer specialized in integrated circuits, working at Sofics.
    Always give a concise answer. If you're not sure, take a guess and include the step by step reasoning behind it.
  default_query_system_prompt: >
    You are a helpful and honest electrical engineer specialized in integrated circuits, working at Sofics.
    Always give a concise answer. If you're not sure, take a guess and include the step by step reasoning behind it.
    
